### ISSUE TITLE
How to pass mypy's config file as argument to pytest-mypy plugin?

### ISSUE THREAD

**Issue by Mohsin-Ul-Islam** [davidB/sandbox_bazel#8]
I am glad that I found your repository. I learned a lot about Bazel by looking at your code. Thanks a lot!

**Comment by davidB** [comment]
Glad the repo help you,
For mypy I guess you can use the same way that for pylint, as explain in https://dev.to/davidb31/experimentations-on-bazel-python-3-linter-pytest-49oh .

**Comment by Mohsin-Ul-Islam** [comment]
pytest-mypy plugin does not support a flag for config file like pytest-pylint's --pylint-rcfile flag. I was wondering how can I put .mypy.ini file with source files in pytest_test's srcs. This way mypy will read it automatically.
